minetest.register_alias("bucket:bucket_empty","bucket:empty")
minetest.register_alias("bucket:bucket_lava","lava:bucket")
minetest.register_alias("bucket:bucket_river_water","water:bucket_river")
minetest.register_alias("bucket:bucket_water","water:bucket")
minetest.register_alias("butterflies:butterfly","bug:butterfly")
minetest.register_alias("butterflies:butterfly_red","bug:butterfly_red")
minetest.register_alias("butterflies:butterfly_violet","bug:butterfly_violet")
minetest.register_alias("butterflies:butterfly_white","bug:butterfly_white")
minetest.register_alias("default:acacia_bush","acacia:bush")
minetest.register_alias("default:acacia_bush_leaves","acacia:bush_leaves")
minetest.register_alias("default:acacia_bush_sapling","acacia:bush_sapling")
minetest.register_alias("default:acacia_bush_stem","acacia:bush_stem")
minetest.register_alias("default:acacia_leaves","acacia:leaves")
minetest.register_alias("default:acacia_log","acacia:log")
minetest.register_alias("default:acacia_sapling","acacia:sapling")
minetest.register_alias("default:acacia_tree","acacia:tree")
minetest.register_alias("default:acacia_wood","acacia:wood")
minetest.register_alias("default:apple", "apple:apple")
minetest.register_alias("default:apple_log","apple:log")
minetest.register_alias("default:apple_mark","apple:mark")
minetest.register_alias("default:apple_tree","apple:tree")
minetest.register_alias("default:aspen_leaves","aspen:leaves")
minetest.register_alias("default:aspen_log","aspen:log")
minetest.register_alias("default:aspen_sapling","aspen:sapling")
minetest.register_alias("default:aspen_tree","aspen:tree")
minetest.register_alias("default:aspen_wood","aspen:wood")
minetest.register_alias("default:axe_bronze","bronze:axe")
minetest.register_alias("default:axe_diamond","diamond:axe")
minetest.register_alias("default:axe_mese","mese:axe")
minetest.register_alias("default:axe_steel","iron:axe")
minetest.register_alias("default:axe_stone","stone:axe")
minetest.register_alias("default:axe_wood","wood:axe")
minetest.register_alias("default:book", "paper:book")
minetest.register_alias("default:book_written", "paper:book_written")
minetest.register_alias("default:bronzeblock", "bronze:block")
minetest.register_alias("default:bronze_ingot", "bronze:ingot")
minetest.register_alias("default:cactus", "cactus:cactus")
minetest.register_alias("default:cave_ice", "snow:cave_ice")
minetest.register_alias("default:chest","chest:chest" )
minetest.register_alias("default:chest_open","chest:chest_open" )
minetest.register_alias("default:chest_locked", "chest:chest")
minetest.register_alias("default:chest_locked_open", "chest:chest_open")
minetest.register_alias("default:coalblock", "coal:block")
minetest.register_alias("default:coal_lump", "coal:lump")
minetest.register_alias("default:cobble", "stone:cobble")
minetest.register_alias("default:copperblock", "copper:block")
minetest.register_alias("default:copper_ingot", "copper:ingot")
minetest.register_alias("default:copper_lump", "copper:lump")
minetest.register_alias("default:coral_brown","coral:brown")
minetest.register_alias("default:coral_cyan","coral:cyan")
minetest.register_alias("default:coral_green","coral:green")
minetest.register_alias("default:coral_orange","coral:orange")
minetest.register_alias("default:coral_pink","coral:pink")
minetest.register_alias("default:coral_skeleton","coral:skeleton")
minetest.register_alias("default:desert_cobble","sand:desert_cobble")
minetest.register_alias("default:desert_sand","sand:desert_sand")
minetest.register_alias("default:desert_sandstone","sand:desert_sandstone")
minetest.register_alias("default:desert_sandstone_block","sand:desert_sandstone_block")
minetest.register_alias("default:desert_sandstone_brick","sand:desert_sandstone_brick")
minetest.register_alias("default:desert_stone","sand:desert_stone")
minetest.register_alias("default:desert_stone_block","sand:desert_stone_block")
minetest.register_alias("default:desert_stonebrick","sand:desert_stonebrick")
minetest.register_alias("default:diamond", "diamond:diamond")
minetest.register_alias("default:diamondblock", "diamond:block")
minetest.register_alias("default:dirt", "dirt:dirt")
minetest.register_alias("default:dirt_with_coniferous_litter", "dirt:dry_litter" )
minetest.register_alias("default:dirt_with_dry_grass", "dirt:grass_dry")
minetest.register_alias("default:dirt_with_grass", "dirt:grass")
minetest.register_alias("default:dirt_with_rainforest_litter", "dirt:litter")
minetest.register_alias("default:dirt_with_snow", "dirt:snow")
minetest.register_alias("default:dry_dirt", "dirt:dry")
minetest.register_alias("default:dry_dirt_with_dry_grass", "dirt:grass_dry")
minetest.register_alias("default:dry_grass_1", "grass:dry")
minetest.register_alias("default:dry_grass_2", "grass:dry_2")
minetest.register_alias("default:dry_grass_3", "grass:dry_3")
minetest.register_alias("default:dry_grass_4", "grass:dry_4")
minetest.register_alias("default:dry_grass_5", "grass:dry_5")
minetest.register_alias("default:emergent_jungle_sapling", "jungle:sapling")
minetest.register_alias("default:emergent_jungle_tree", "jungle:sapling")
minetest.register_alias("default:fence_acacia_wood", "acacia:fence")
minetest.register_alias("default:fence_aspen_wood", "aspen:fence")
minetest.register_alias("default:fence_junglewood", "jungle:fence")
minetest.register_alias("default:fence_pine_wood", "pine:fence")
minetest.register_alias("default:fence_wood", "apple:fence")
minetest.register_alias("default:flint" , "fire:flint")
minetest.register_alias("default:furnace", "furnace:furnace")
minetest.register_alias("default:furnace_active",  "furnace:furnace_active")
minetest.register_alias("default:glass", "glass:glass")
minetest.register_alias("default:goldblock", "gold:block")
minetest.register_alias("default:gold_ingot", "gold:ingot")
minetest.register_alias("default:gold_lump", "gold:lump")
minetest.register_alias("default:grass_1", "grass:grass_1" )
minetest.register_alias("default:grass_2", "grass:grass_2")
minetest.register_alias("default:grass_3", "grass:grass_3")
minetest.register_alias("default:grass_4", "grass:grass_4")
minetest.register_alias("default:grass_5", "grass:grass_5")
minetest.register_alias("default:gravel", "gravel:gravel")
minetest.register_alias("default:ice", "snow:ice")
minetest.register_alias("default:iron_lump", "iron:lump")
minetest.register_alias("default:junglegrass","grass:jungle")
minetest.register_alias("default:jungleleaves","jungle:leaves")
minetest.register_alias("default:jungle_log", "jungle:log")
minetest.register_alias("default:junglesapling","jungle:sapling")
minetest.register_alias("default:jungle_tree", "jungle:tree")
minetest.register_alias("default:jungletree","jungle:tree")
minetest.register_alias("default:junglewood","jungle:wood")
minetest.register_alias("default:key", "lock:key")
minetest.register_alias("default:ladder", "wood:ladder")
minetest.register_alias("default:ladder_steel", "iron:ladder")
minetest.register_alias("default:ladder_wood", "wood:ladder")
minetest.register_alias("default:large_cactus", "cactus:cactus")
minetest.register_alias("default:large_cactus_seedling", "cactus:large_seedling")
minetest.register_alias("default:lava_flowing", "lava:flowing")
minetest.register_alias("default:lava_source", "lava:source")
minetest.register_alias("default:leaves", "apple:leaves")
minetest.register_alias("default:marram_grass", "grass:marram")
minetest.register_alias("default:marram_grass_2", "grass:marram_2")
minetest.register_alias("default:marram_grass_3", "grass:marram_3")
minetest.register_alias("default:mese", "mese:ore" )
minetest.register_alias("default:mese_block", "mese:block")
minetest.register_alias("default:mese_crystal", "mese:crystal")
minetest.register_alias("default:mese_crystal_fragment", "mese:crystal_fragment")
minetest.register_alias("default:meselamp", "mese:lamp")
minetest.register_alias("default:mossycobble", "stone:mossycobble")
minetest.register_alias("default:obsidian", "glass:obsidian")
minetest.register_alias("default:obsidian_block", "glass:obsidian_block")
minetest.register_alias("default:obsidianbrick", "glass:obsidian_brick")
minetest.register_alias("default:obsidian_glass", "glass:obsidian")
minetest.register_alias("default:paper", "paper:paper")
minetest.register_alias("default:papyrus", "papyrus:papyrus")
minetest.register_alias("default:permafrost", "snow:permafrost")
minetest.register_alias("default:permafrost_with_moss", "default:permafrost_with_moss")
minetest.register_alias("default:permafrost_with_stones", "default:permafrost_with_stones")
minetest.register_alias("default:pick_bronze","bronze:pick")
minetest.register_alias("default:pick_diamond","diamond:pick")
minetest.register_alias("default:pick_mese","mese:pick")
minetest.register_alias("default:pick_steel","iron:pick")
minetest.register_alias("default:pick_stone","stone:pick")
minetest.register_alias("default:pick_wood","wood:pick")
minetest.register_alias("default:pine_log","pine:log")
minetest.register_alias("default:pine_needles","pine:needles")
minetest.register_alias("default:pine_sapling","pine:sapling")
minetest.register_alias("default:pine_tree","pine:tree")
minetest.register_alias("default:pine_wood","pine:wood")
minetest.register_alias("default:river_water_flowing","water:river_flowing")
minetest.register_alias("default:river_water_source","water:river_source")
minetest.register_alias("default:sand", "sand:sand")
minetest.register_alias("default:sandstone", "sand:sandstone")
minetest.register_alias("default:sandstone_block", "sand:sandstone_block")
minetest.register_alias("default:sandstonebrick", "sand:sandstone_brick")
minetest.register_alias("default:sapling", "apple:sapling")
minetest.register_alias("default:shovel_bronze","bronze:shovel")
minetest.register_alias("default:shovel_diamond","diamond:shovel")
minetest.register_alias("default:shovel_mese","mese:shovel")
minetest.register_alias("default:shovel_steel","iron:shovel")
minetest.register_alias("default:shovel_stone","stone:shovel")
minetest.register_alias("default:shovel_wood","wood:shovel")
minetest.register_alias("default:sign_wall_wood","wood:sign")
minetest.register_alias("default:sign_wall_steel","iron:sign")
minetest.register_alias("default:silver_sand","sand:silver")
minetest.register_alias("default:silver_sandstone","sand:silver_sandstone")
minetest.register_alias("default:silver_sandstone_block","sand:silver_sandstone_block")
minetest.register_alias("default:silver_sandstone_brick","sand:silver_sandstone_brick")
minetest.register_alias("default:skeleton_key", "key:blank")
minetest.register_alias("default:snow", "snow:snow")
minetest.register_alias("default:snowblock", "snow:block")
minetest.register_alias("default:steelblock", "iron:block")
minetest.register_alias("default:steel_ingot", "iron:ingot")
minetest.register_alias("default:stick", "wood:stick")
minetest.register_alias("default:stone", "stone:stone")
minetest.register_alias("default:stone_block", "stone:block")
minetest.register_alias("default:stonebrick", "stone:brick")
minetest.register_alias("default:stone_with_coal", "coal:stone_with_coal")
minetest.register_alias("default:stone_with_copper", "copper:stone_with_copper")
minetest.register_alias("default:stone_with_diamond", "diamond:stone_with_diamond")
minetest.register_alias("default:stone_with_gold", "gold:stone_with_gold")
minetest.register_alias("default:stone_with_iron", "iron:stone_with_iron")
minetest.register_alias("default:stone_with_mese", "mese:stone_with_mese")
minetest.register_alias("default:stone_with_tin", "tin:stone_with_tin")
minetest.register_alias("default:sword_bronze","bronze:sword")
minetest.register_alias("default:sword_diamond","diamond:sword")
minetest.register_alias("default:sword_mese","mese:sword")
minetest.register_alias("default:sword_steel","iron:sword")
minetest.register_alias("default:sword_stone","stone:sword")
minetest.register_alias("default:sword_wood","wood:sword")
minetest.register_alias("default:tinblock", "tin:block")
minetest.register_alias("default:tin_ingot", "tin:ingot")
minetest.register_alias("default:tin_lump", "tin:lump")
minetest.register_alias("default:torch", "torch:torch")
minetest.register_alias("default:torch_ceiling", "torch:torch_ceiling")
minetest.register_alias("default:torch_wall", "torch:torch_ceiling")
minetest.register_alias("default:tree", "apple:tree")
minetest.register_alias("default:water_flowing", "water:flowing")
minetest.register_alias("default:waterlily", "flower:waterlily")
minetest.register_alias("default:water_source", "water:source")
minetest.register_alias("default:wood", "apple:wood")
minetest.register_alias("fireflies:bug_net", "bug:net")
minetest.register_alias("fireflies:firefly", "bug:firefly")
minetest.register_alias("flowers:dandelion_white","flower:dandelion_white")
minetest.register_alias("flowers:dandelion_yellow","flower:dandelion_yellow")
minetest.register_alias("flowers:flower_dandelion_white","flower:dandelion_white")
minetest.register_alias("flowers:flower_dandelion_yellow","flower:dandelion_yellow")
minetest.register_alias("flowers:flower_geranium","flower:geranium")
minetest.register_alias("flowers:flower_rose","flower:rose")
minetest.register_alias("flowers:flower_tulip","flower:tulip")
minetest.register_alias("flowers:flower_viola","flower:viola")
minetest.register_alias("flowers:geranium","flower:geranium")
minetest.register_alias("flowers:mushroom_brown","mushroom:brown")
minetest.register_alias("flowers:mushroom_red","mushroom:red")
minetest.register_alias("flowers:rose","flower:rose")
minetest.register_alias("flowers:tulip","flower:tulip")
minetest.register_alias("flowers:viola","flower:viola")
minetest.register_alias("flowers:waterlily","flower:waterlily")
minetest.register_alias("vessels:drinking_glass","vessel:drinking_glass")
minetest.register_alias("vessels:glass_bottle","vessel:glass_bottle")
minetest.register_alias("vessels:glass_fragments","vessel:glass_fragments")
minetest.register_alias("vessels:shelf","vessel:shelf")
minetest.register_alias("vessels:steel_bottle","vessel:steel_bottle")
minetest.register_alias("walls:cobble", "stone:cobble_wall")
minetest.register_alias("walls:mossycobble", "stone:mossycobble_wall")
